# Generated by Django 5.0.7 on 2024-08-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='bloodGroupId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donors',
            name='distrcitId',
            field=models.IntegerField(),
        ),
    ]
