# Generated by Django 5.0.7 on 2024-08-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_alter_donors_bloodgroupid_alter_donors_distrcitid'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='email',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='donors',
            name='mobile',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='donors',
            name='name',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
